### ISSUE TITLE
Odd Serverminer Crash

### ISSUE THREAD

**Issue by Spooktackular** [Vetpetmon-Labs/Wyrms-of-Nyrus#20] opened 2022-09-16 21:41 UTC
Not sure whats going on here, but every time i open my server i get this error

Wyrms of Nyrus | /mods/wyrmsofnyrus-1.12.2-0.1.36.jar | 16th Sep 2022 15:32 PM | net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wyrms of Nyrus (wyrmsofnyrus)

[latest.log](https://github.com/Vetpetmon-Labs/Wyrms-of-Nyrus/files/9588243/latest.log)

Here's the log, im using serverminer with the coal plan, if that matters.

**Comment by Vetpetmon** [comment] 2022-09-16 22:15
`[22:32:55] [Server thread/INFO] [wyrmsofnyrus]: SynapseLib is on version 0.26
[22:32:55] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Wyrms of Nyrus (wyrmsofnyrus)

Caused by: java.lang.NullPointerException
	at com.vetpetmon.wyrmsofnyrus.config.ConfigLib.reloadConfig(ConfigLib.java:68) ~[ConfigLib.class:1.12.2-0.1.36]
	at com.vetpetmon.wyrmsofnyrus.wyrmsofnyrus.preInit(wyrmsofnyrus.java:67) ~[wyrmsofnyrus.class:1.12.2-0.1.36]`
	
What does your `/config` folder look like? This is before Hostile Skies, so the config should generate in wyrms.cfg directly into the config folder.

It could be that the write permissions are not properly defined, so the mod fails to write/read the config, and throws a nullpointer exception.

This may happen for the following reasons (starred is most probable, look into those first):

- Improperly configured server
- Read/write permissions not granted*
- Outdated Wyrms of Nyrus build (or config not reset)*
- Pirated/cracked servers or clients

**Comment by Vetpetmon** [comment] 2022-09-16 22:53
The Forge and Java (JRE) version could have something to do with this, though I do not have access to any of the server information. Putting any and all information about the server and what you've done through the server's management GUI would be greatly appreciated.

**Comment by Vetpetmon** [comment] 2022-11-28 00:58
0.1.5 is confirmed to include a failsafe system in case if configuration files fail to load. The game will load failsafes first, then try configs before ultimately moving to the next steps in the loading process, without crashing.

If this gets fixed or not, I can only hope.

**Comment by Vetpetmon** [comment] 2023-02-05 19:46
![image](https://user-images.githubusercontent.com/10699805/216841213-b5f43064-fa30-4c1a-be20-48534f519eb9.png)
Has been fixed entirely in 0.2.61, my bad.

Caused because getDataDir() returned null on the server proxy, but returned something only on the client proxy.

**Closed by Vetpetmon** 2023-02-05 19:46 UTC
Labels: question, Critical
